"""lesson_topic

Revision ID: 21405428e3c3
Revises: c99faeee99e3
Create Date: 2026-05-17 19:57:01.560300

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '21405428e3c3'
down_revision: str | Sequence[str] | None = 'c99faeee99e3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'lessons',
        sa.Column(
            'topic',
            sa.String(length=100),
            server_default=sa.text("''"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'topic')
    # ### end Alembic commands ###
