"""Indexes

Revision ID: 44f71284a257
Revises: 7a0552a6591e
Create Date: 2026-04-29 20:44:27.421298

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '44f71284a257'
down_revision: str | Sequence[str] | None = '7a0552a6591e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f('ix_attendance_lesson_id'),
        'attendance',
        ['lesson_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_attendance_student_id'),
        'attendance',
        ['student_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_course_teacher_students_course_teacher_id'),
        'course_teacher_students',
        ['course_teacher_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_course_teacher_students_student_id'),
        'course_teacher_students',
        ['student_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_course_teachers_course_id'),
        'course_teachers',
        ['course_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_course_teachers_teacher_id'),
        'course_teachers',
        ['teacher_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_courses_subject_id'),
        'courses',
        ['subject_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_feedback_author_id'),
        'feedback',
        ['author_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_feedback_course_id'),
        'feedback',
        ['course_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_feedback_teacher_id'),
        'feedback',
        ['teacher_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_groups_course_id'),
        'groups',
        ['course_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_groups_default_cabinet_id'),
        'groups',
        ['default_cabinet_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_lessons_cabinet_id'),
        'lessons',
        ['cabinet_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_lessons_conducted_by_id'),
        'lessons',
        ['conducted_by_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_lessons_course_teacher_student_id'),
        'lessons',
        ['course_teacher_student_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_lessons_group_id'),
        'lessons',
        ['group_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_organization_members_user_id'),
        'organization_members',
        ['user_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_organizations_created_by_id'),
        'organizations',
        ['created_by_id'],
        unique=False,
    )
    op.create_index(
        'ix_organizations_name_trgm',
        'organizations',
        ['name'],
        unique=False,
        postgresql_ops={'name': 'gin_trgm_ops'},
        postgresql_using='gin',
    )
    op.create_index(
        'ix_organizations_slug_trgm',
        'organizations',
        ['slug'],
        unique=False,
        postgresql_ops={'slug': 'gin_trgm_ops'},
        postgresql_using='gin',
    )
    op.create_index(
        op.f('ix_payments_created_by_id'),
        'payments',
        ['created_by_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_payments_student_group_id'),
        'payments',
        ['student_group_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_payments_lesson_id'),
        'payments',
        ['lesson_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_student_groups_group_id'),
        'student_groups',
        ['group_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_student_groups_student_id'),
        'student_groups',
        ['student_id'],
        unique=False,
    )
    op.create_index(
        'ix_users_email_trgm',
        'users',
        ['email'],
        unique=False,
        postgresql_ops={'email': 'gin_trgm_ops'},
        postgresql_using='gin',
    )
    op.create_index(
        'ix_users_fullname_trgm',
        'users',
        ['fullname'],
        unique=False,
        postgresql_ops={'fullname': 'gin_trgm_ops'},
        postgresql_using='gin',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_users_fullname_trgm',
        table_name='users',
        postgresql_ops={'fullname': 'gin_trgm_ops'},
        postgresql_using='gin',
    )
    op.drop_index(
        'ix_users_email_trgm',
        table_name='users',
        postgresql_ops={'email': 'gin_trgm_ops'},
        postgresql_using='gin',
    )
    op.drop_index(
        op.f('ix_student_groups_student_id'),
        table_name='student_groups',
    )
    op.drop_index(
        op.f('ix_student_groups_group_id'),
        table_name='student_groups',
    )
    op.drop_index(op.f('ix_payments_lesson_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_student_group_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_by_id'), table_name='payments')
    op.drop_index(
        'ix_organizations_slug_trgm',
        table_name='organizations',
        postgresql_ops={'slug': 'gin_trgm_ops'},
        postgresql_using='gin',
    )
    op.drop_index(
        'ix_organizations_name_trgm',
        table_name='organizations',
        postgresql_ops={'name': 'gin_trgm_ops'},
        postgresql_using='gin',
    )
    op.drop_index(
        op.f('ix_organizations_created_by_id'),
        table_name='organizations',
    )
    op.drop_index(
        op.f('ix_organization_members_user_id'),
        table_name='organization_members',
    )
    op.drop_index(op.f('ix_lessons_group_id'), table_name='lessons')
    op.drop_index(
        op.f('ix_lessons_course_teacher_student_id'),
        table_name='lessons',
    )
    op.drop_index(op.f('ix_lessons_conducted_by_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_cabinet_id'), table_name='lessons')
    op.drop_index(op.f('ix_groups_default_cabinet_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_course_id'), table_name='groups')
    op.drop_index(op.f('ix_feedback_teacher_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_course_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_author_id'), table_name='feedback')
    op.drop_index(op.f('ix_courses_subject_id'), table_name='courses')
    op.drop_index(
        op.f('ix_course_teachers_teacher_id'),
        table_name='course_teachers',
    )
    op.drop_index(
        op.f('ix_course_teachers_course_id'),
        table_name='course_teachers',
    )
    op.drop_index(
        op.f('ix_course_teacher_students_student_id'),
        table_name='course_teacher_students',
    )
    op.drop_index(
        op.f('ix_course_teacher_students_course_teacher_id'),
        table_name='course_teacher_students',
    )
    op.drop_index(op.f('ix_attendance_student_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_lesson_id'), table_name='attendance')
    # ### end Alembic commands ###
    op.execute('DROP EXTENSION IF EXISTS pg_trgm')
