"""uq_users_email

Revision ID: c99faeee99e3
Revises: 44f71284a257
Create Date: 2026-05-13 19:14:41.936777

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c99faeee99e3'
down_revision: str | Sequence[str] | None = '44f71284a257'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(
        'uq_users_email',
        'users',
        ['email'],
        unique=True,
        postgresql_where='is_active = true',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'uq_users_email',
        table_name='users',
        postgresql_where='is_active = true',
    )
    op.create_unique_constraint(
        op.f('users_email_key'),
        'users',
        ['email'],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
