/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PoliticsRouteImport } from './routes/politics'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutSubjectsRouteImport } from './routes/_layout/subjects'
import { Route as LayoutScheduleRouteImport } from './routes/_layout/schedule'
import { Route as LayoutProfileRouteImport } from './routes/_layout/profile'
import { Route as LayoutPaymentsRouteImport } from './routes/_layout/payments'
import { Route as LayoutOrgsRouteImport } from './routes/_layout/orgs'
import { Route as LayoutNotificationsRouteImport } from './routes/_layout/notifications'
import { Route as LayoutMembersRouteImport } from './routes/_layout/members'
import { Route as LayoutIndividualsRouteImport } from './routes/_layout/individuals'
import { Route as LayoutGroupsRouteImport } from './routes/_layout/groups'
import { Route as LayoutFeedbackRouteImport } from './routes/_layout/feedback'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutCoursesRouteImport } from './routes/_layout/courses'
import { Route as LayoutAttendanceRouteImport } from './routes/_layout/attendance'
import { Route as LayoutAddressesRouteImport } from './routes/_layout/addresses'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticsRoute = PoliticsRouteImport.update({
  id: '/politics',
  path: '/politics',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSubjectsRoute = LayoutSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutScheduleRoute = LayoutScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileRoute = LayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPaymentsRoute = LayoutPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrgsRoute = LayoutOrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNotificationsRoute = LayoutNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMembersRoute = LayoutMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutIndividualsRoute = LayoutIndividualsRouteImport.update({
  id: '/individuals',
  path: '/individuals',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGroupsRoute = LayoutGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFeedbackRoute = LayoutFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCoursesRoute = LayoutCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAttendanceRoute = LayoutAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAddressesRoute = LayoutAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/politics': typeof PoliticsRoute
  '/register': typeof RegisterRoute
  '/addresses': typeof LayoutAddressesRoute
  '/attendance': typeof LayoutAttendanceRoute
  '/courses': typeof LayoutCoursesRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/feedback': typeof LayoutFeedbackRoute
  '/groups': typeof LayoutGroupsRoute
  '/individuals': typeof LayoutIndividualsRoute
  '/members': typeof LayoutMembersRoute
  '/notifications': typeof LayoutNotificationsRoute
  '/orgs': typeof LayoutOrgsRoute
  '/payments': typeof LayoutPaymentsRoute
  '/profile': typeof LayoutProfileRoute
  '/schedule': typeof LayoutScheduleRoute
  '/subjects': typeof LayoutSubjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/politics': typeof PoliticsRoute
  '/register': typeof RegisterRoute
  '/addresses': typeof LayoutAddressesRoute
  '/attendance': typeof LayoutAttendanceRoute
  '/courses': typeof LayoutCoursesRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/feedback': typeof LayoutFeedbackRoute
  '/groups': typeof LayoutGroupsRoute
  '/individuals': typeof LayoutIndividualsRoute
  '/members': typeof LayoutMembersRoute
  '/notifications': typeof LayoutNotificationsRoute
  '/orgs': typeof LayoutOrgsRoute
  '/payments': typeof LayoutPaymentsRoute
  '/profile': typeof LayoutProfileRoute
  '/schedule': typeof LayoutScheduleRoute
  '/subjects': typeof LayoutSubjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/politics': typeof PoliticsRoute
  '/register': typeof RegisterRoute
  '/_layout/addresses': typeof LayoutAddressesRoute
  '/_layout/attendance': typeof LayoutAttendanceRoute
  '/_layout/courses': typeof LayoutCoursesRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/feedback': typeof LayoutFeedbackRoute
  '/_layout/groups': typeof LayoutGroupsRoute
  '/_layout/individuals': typeof LayoutIndividualsRoute
  '/_layout/members': typeof LayoutMembersRoute
  '/_layout/notifications': typeof LayoutNotificationsRoute
  '/_layout/orgs': typeof LayoutOrgsRoute
  '/_layout/payments': typeof LayoutPaymentsRoute
  '/_layout/profile': typeof LayoutProfileRoute
  '/_layout/schedule': typeof LayoutScheduleRoute
  '/_layout/subjects': typeof LayoutSubjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/politics'
    | '/register'
    | '/addresses'
    | '/attendance'
    | '/courses'
    | '/dashboard'
    | '/feedback'
    | '/groups'
    | '/individuals'
    | '/members'
    | '/notifications'
    | '/orgs'
    | '/payments'
    | '/profile'
    | '/schedule'
    | '/subjects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/politics'
    | '/register'
    | '/addresses'
    | '/attendance'
    | '/courses'
    | '/dashboard'
    | '/feedback'
    | '/groups'
    | '/individuals'
    | '/members'
    | '/notifications'
    | '/orgs'
    | '/payments'
    | '/profile'
    | '/schedule'
    | '/subjects'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/politics'
    | '/register'
    | '/_layout/addresses'
    | '/_layout/attendance'
    | '/_layout/courses'
    | '/_layout/dashboard'
    | '/_layout/feedback'
    | '/_layout/groups'
    | '/_layout/individuals'
    | '/_layout/members'
    | '/_layout/notifications'
    | '/_layout/orgs'
    | '/_layout/payments'
    | '/_layout/profile'
    | '/_layout/schedule'
    | '/_layout/subjects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  PoliticsRoute: typeof PoliticsRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politics': {
      id: '/politics'
      path: '/politics'
      fullPath: '/politics'
      preLoaderRoute: typeof PoliticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/subjects': {
      id: '/_layout/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof LayoutSubjectsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/schedule': {
      id: '/_layout/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof LayoutScheduleRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile': {
      id: '/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/payments': {
      id: '/_layout/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof LayoutPaymentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/orgs': {
      id: '/_layout/orgs'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof LayoutOrgsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/notifications': {
      id: '/_layout/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof LayoutNotificationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/members': {
      id: '/_layout/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof LayoutMembersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/individuals': {
      id: '/_layout/individuals'
      path: '/individuals'
      fullPath: '/individuals'
      preLoaderRoute: typeof LayoutIndividualsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/groups': {
      id: '/_layout/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof LayoutGroupsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/feedback': {
      id: '/_layout/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof LayoutFeedbackRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/courses': {
      id: '/_layout/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof LayoutCoursesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/attendance': {
      id: '/_layout/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof LayoutAttendanceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/addresses': {
      id: '/_layout/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof LayoutAddressesRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAddressesRoute: typeof LayoutAddressesRoute
  LayoutAttendanceRoute: typeof LayoutAttendanceRoute
  LayoutCoursesRoute: typeof LayoutCoursesRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutFeedbackRoute: typeof LayoutFeedbackRoute
  LayoutGroupsRoute: typeof LayoutGroupsRoute
  LayoutIndividualsRoute: typeof LayoutIndividualsRoute
  LayoutMembersRoute: typeof LayoutMembersRoute
  LayoutNotificationsRoute: typeof LayoutNotificationsRoute
  LayoutOrgsRoute: typeof LayoutOrgsRoute
  LayoutPaymentsRoute: typeof LayoutPaymentsRoute
  LayoutProfileRoute: typeof LayoutProfileRoute
  LayoutScheduleRoute: typeof LayoutScheduleRoute
  LayoutSubjectsRoute: typeof LayoutSubjectsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAddressesRoute: LayoutAddressesRoute,
  LayoutAttendanceRoute: LayoutAttendanceRoute,
  LayoutCoursesRoute: LayoutCoursesRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutFeedbackRoute: LayoutFeedbackRoute,
  LayoutGroupsRoute: LayoutGroupsRoute,
  LayoutIndividualsRoute: LayoutIndividualsRoute,
  LayoutMembersRoute: LayoutMembersRoute,
  LayoutNotificationsRoute: LayoutNotificationsRoute,
  LayoutOrgsRoute: LayoutOrgsRoute,
  LayoutPaymentsRoute: LayoutPaymentsRoute,
  LayoutProfileRoute: LayoutProfileRoute,
  LayoutScheduleRoute: LayoutScheduleRoute,
  LayoutSubjectsRoute: LayoutSubjectsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  PoliticsRoute: PoliticsRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
